import Head from "next/head";
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import Navbar from "@/components/Navbar";
import Link from "next/link";
import usePaths from "@/hooks/usePaths";
import type { NextPageContext } from "next";

export default function Home() {
  const { t } = useTranslation('common');
  const paths = usePaths();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Navbar />
        <h1>{t('pages.home.heading')}</h1>
        <Link href={paths.signIn} >{t('paths.signIn')}</Link>

      </main >
    </>
  );
}

export async function getStaticProps({ locale = 'fi' }: NextPageContext) {
  return {
    props: {
      ...(await serverSideTranslations(locale, [
        'common',
      ])),
    },
  }
}